plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'checkstyle'
    id 'pmd'
    id 'com.diffplug.spotless' version '8.9.0'
}

group = 'edu.nus.cs3227'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'edu.nus.cs3227.mp1.HelloWorldApp'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.20.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

spotless {
    java {
        googleJavaFormat()
        target 'src/*/java/**/*.java'
    }
}

checkstyle {
    toolVersion = '12.1.0'
    configFile = file('config/checkstyle/checkstyle.xml')
}

pmd {
    toolVersion = '7.25.0'
    ruleSetFiles = files('config/pmd/ruleset.xml')
    ruleSets = []
}

tasks.named('pmdTest') {
    enabled = false
}

jacoco {
    toolVersion = '0.8.14'
}

tasks.named('jacocoTestCoverageVerification') {
    violationRules {
        rule {
            limit {
                counter = 'INSTRUCTION'
                value = 'COVEREDRATIO'
                minimum = 0.80
            }
        }
    }
}

tasks.named('check') {
    dependsOn tasks.named('jacocoTestCoverageVerification')
}

tasks.named('jacocoTestReport') {
    reports {
        xml.required = true
        html.required = true
    }
}
